import { displayTerminal } from './components/apps/terminal';
import { displayContentManager } from './components/apps/content-manager';
import { displaySettings } from './components/apps/settings';
import { displayContact } from './components/apps/contact';
import {
    displayAbout,
    displayProjects,
    displayExperience,
    displayWriting,
    displayResume,
} from './components/apps/alex';

const apps = [
    {
        id: "about",
        title: "About",
        description: "System profile, engineering focus, and background.",
        icon: './themes/Yaru/system/user-home.png',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayAbout,
    },
    {
        id: "projects",
        title: "Projects",
        description: "Project directory with architecture and impact.",
        icon: './themes/Yaru/status/projects.svg',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayProjects,
    },
    {
        id: "experience",
        title: "Experience",
        description: "Career log and measurable engineering outcomes.",
        icon: './themes/Yaru/status/education.svg',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayExperience,
    },
    {
        id: "writing",
        title: "Writing",
        description: "Technical notes directory.",
        icon: './themes/Yaru/apps/gedit.png',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayWriting,
    },
    {
        id: "resume",
        title: "Resume",
        description: "View and download resume.pdf.",
        icon: './themes/Yaru/status/download.svg',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayResume,
    },
    {
        id: "terminal",
        title: "Terminal",
        description: "Explore Alex OS through the command line.",
        icon: './themes/Yaru/apps/bash.png',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayTerminal,
    },
    {
        id: "contact",
        title: "Contact",
        description: "Email and professional links.",
        icon: './themes/Yaru/apps/gedit.png',
        disabled: false,
        favourite: true,
        desktop_shortcut: true,
        screen: displayContact,
    },
    {
        id: "content",
        title: "Content",
        description: "Edit the live portfolio bundle and export it locally.",
        icon: './themes/Yaru/apps/gedit.png',
        disabled: false,
        favourite: false,
        desktop_shortcut: false,
        internalOnly: true,
        screen: displayContentManager,
    },
    {
        id: "settings",
        title: "Settings",
        description: "Appearance, motion, and experience controls.",
        icon: './themes/Yaru/apps/gnome-control-center.png',
        disabled: false,
        favourite: true,
        desktop_shortcut: false,
        screen: displaySettings,
    },
]

export default apps;