import identity from "../config/identity";

const portfolioContent = {
  profile: {
    name: identity.name,
    title: identity.professionalTitle,
    summary: identity.professionalSummary,
    location: identity.location,
    phone: identity.phone,
  },
  focusAreas: [
    "Backend Engineering",
    "Distributed Systems",
    "API Performance",
    "Cloud Infrastructure",
    "Financial Workflows",
    "ERP Integrations",
    "Healthcare Systems",
  ],
  experience: [
    {
      company: "Savannah Informatics Limited",
      role: "Senior Backend Engineer",
      period: "September 2025 - Present",
      summary: "Designs backend services for healthcare billing, ERP synchronization, payment processing, and financial workflows while owning production performance and observability.",
      highlights: [
        "Reduced production database queries from 594 to 6 using advanced Django ORM optimization.",
        "Optimized an organisation-unit workflow from 819 queries to 36, reducing execution time from 10.6s to 3.2s.",
        "Reduced API response time for a production payment endpoint from 19 seconds to 220ms through database optimization and serializer redesign.",
        "Designed resilient asynchronous processing pipelines using Celery, idempotency controls, retries, and event-driven architecture.",
        "Led backend performance engineering initiatives through profiling, Redis caching, ORM optimization, and database tuning.",
        "Contributed to end-to-end production observability with Grafana dashboards and Prometheus-based alerts for backend services running on Kubernetes.",
      ],
      technologies: ["Python", "Django", "Django REST Framework", "PostgreSQL", "Redis", "Celery", "Kubernetes", "Grafana", "Prometheus", "AWS"],
    },
    {
      company: "Getotech Ltd",
      role: "Founder & Lead Software Engineer",
      period: "September 2023 - Present",
      summary: "Founded Getotech to build software and IoT solutions for transportation, education, and business automation.",
      highlights: [
        "Architect cloud-native backend platforms and an IoT-powered passenger information system.",
        "Build across Python, C#, Django, Redis, Docker, AWS, and ESP32 for transportation and business systems.",
      ],
      technologies: ["Python", "C#/.NET", "Django", "Redis", "Docker", "AWS", "ESP32"],
    },
    {
      company: "A Million Techies",
      role: "Co-Founder & Backend Engineer",
      period: "November 2024 - Present",
      summary: "Co-founded a technology community empowering African software engineers through mentorship, technical writing, backend platform development, and practical learning.",
      highlights: [
        "Built and maintained backend platform features supporting community learning, content delivery, and member engagement.",
        "Contributed to mentorship and practical engineering education alongside platform development.",
      ],
      technologies: ["Python", "Django", "PostgreSQL", "Docker", "AWS", "Backend Platform Development"],
    },
    {
      company: "Greenlead Africa",
      role: "Backend Developer & Integrations Engineer",
      period: "2024",
      summary: "Earlier experience listed in the resume.",
      highlights: [],
      technologies: [],
    },
    {
      company: "Independent",
      role: "Freelance Backend & Cloud Engineer",
      period: "2023 - Present",
      summary: "Earlier experience listed in the resume.",
      highlights: [],
      technologies: [],
    },
    {
      company: "Machini Technologies",
      role: "Software Engineer Intern -> Junior Software Engineer",
      period: "2022 - 2023",
      summary: "Earlier experience listed in the resume.",
      highlights: [],
      technologies: [],
    },
  ],
  projects: [
    {
      id: "learning-management-platform",
      name: "Learning Management Platform",
      overview: "Cloud-native learning platform supporting courses, learner progress, and certificates.",
      problem: "Deliver a learning platform capable of handling structured course delivery, learner progress tracking, and certificate workflows.",
      solution: "Built the platform using Python, Django, React, PostgreSQL, Docker, and AWS with backend services for courses, progress tracking, and learner-facing workflows.",
      architecture: "Python and Django backend paired with React frontend, PostgreSQL persistence, containerized delivery with Docker, and AWS-hosted infrastructure.",
      technologies: ["Python", "Django", "React", "PostgreSQL", "Docker", "AWS"],
      impact: "Supports course delivery, learner progress, and certificate management across deployed learning products.",
      links: [
        { label: "A Million Techies LMS", url: "https://learn.amilliontechies.com/" },
        { label: "Study Buddy", url: "https://www.studybuddy.africa/" },
      ],
    },
    {
      id: "ai-missing-persons-recognition",
      name: "AI Missing Persons Recognition",
      overview: "Facial recognition platform for identity matching.",
      problem: "Enable identity matching workflows for missing persons scenarios using computer vision.",
      solution: "Built a facial recognition platform in Python using OpenCV and PyTorch for image-based identity matching.",
      architecture: "Python application layer with OpenCV image processing and PyTorch model workflows.",
      technologies: ["Python", "OpenCV", "PyTorch"],
      impact: "Demonstrates practical applied AI system development beyond conventional CRUD systems.",
      links: [
        { label: "GitHub Repository", url: "https://github.com/Alekita254/Attendance" },
      ],
    },
    {
      id: "smart-passenger-information-system",
      name: "Smart Passenger Information System",
      overview: "IoT platform for public transport displays and real-time synchronization.",
      problem: "Provide transport operators and passengers with synchronized, real-time display information.",
      solution: "Built an IoT-enabled passenger information system integrating ESP32 devices with AWS-backed synchronization workflows.",
      architecture: "Edge devices powered by ESP32 communicating with cloud services to keep transport displays synchronized in real time.",
      technologies: ["ESP32", "AWS", "Real-time Synchronization", "IoT"],
      impact: "Extends Alex's backend and systems work into physical infrastructure and transport automation.",
      links: [],
    },
  ],
  skills: {
    languages: ["Python", "Go", "C#/.NET"],
    backend: ["Django", "Django REST Framework", "REST APIs", "Celery"],
    databases: ["PostgreSQL", "Redis"],
    infrastructure: ["AWS", "Docker", "Kubernetes", "Linux", "Grafana", "Prometheus", "CI/CD"],
    engineering: ["Distributed Systems", "Performance Engineering", "Cloud Architecture", "Financial Systems", "ERP Integrations", "Asynchronous Messaging", "System Design"],
  },
  education: [
    {
      institution: "Tharaka University",
      credential: "B.Sc. Computer Science",
      period: "",
      notes: "",
    },
  ],
  certifications: [
    "AWS Cloud Practitioner",
    "Oracle DevOps",
    "Oracle Vector Search",
    "Cisco CyberOps Associate",
    "Founders Factory Africa",
  ],
  writing: [],
  writingNote: "Technical notes and ideas will appear here.",
  community: [
    {
      name: "A Million Techies",
      role: "Co-Founder & Backend Engineer",
      summary: "Technology community empowering African software engineers through mentorship, technical writing, backend platform development, and practical learning.",
    },
  ],
  interests: ["Generative AI & LLMs", "NLP & Transformer Models", "Data Engineering & MLOps", "Full-Stack & DevOps"],
  socialLinks: [
    { label: "GitHub", url: identity.github },
    { label: "Email", url: `mailto:${identity.email}` },
    { label: "A Million Techies LMS", url: "https://learn.amilliontechies.com/" },
  ],
};

export default portfolioContent;
